version: '3'

services:
  django_app:
    env_file:
      - ./Restaurant/.env
    build: .
    volumes:
      - app_volume:/djangoapp
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - app_volume:/djangoapp
    ports:
      - "80:80"
    depends_on:
      - django_app
volumes:
  app_volume:


