# Generated by Django 4.0.2 on 2023-03-10 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DietTypeId', models.CharField(max_length=5)),
                ('DietTypeName', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'menu_diettype',
            },
        ),
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MenuSectionName', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'menu_menusection',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MealPicture', models.ImageField(upload_to='images/')),
                ('MealName', models.CharField(max_length=30, unique=True)),
                ('MealIngredients', models.CharField(max_length=100)),
                ('MealPrice', models.IntegerField(default=0)),
                ('MealDietType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.diettype')),
                ('MealSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menusection')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('menu.meal',),
        ),
    ]
