# Generated by Django 4.0.2 on 2023-03-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='MealName',
            field=models.CharField(max_length=30),
        ),
    ]
